.PHONY=all clean

all:
	make -C File_Management
	make -C IPC
	make -C Process_Thread_Management
	make -C Syncronization

clean:
	make -C File_Management clean
	make -C IPC clean
	make -C Process_Thread_Management clean
	make -C Syncronization clean


